config/routes.rb
Rails.application.routes.draw do

  root to: 'application#top_page'

  get 'crawl' => 'application#crawl'

  resources :years, only: [:index, :show] do
    get 'courses/search' => 'courses#search'
    resources :courses, only: [:index, :show] do
      resources :comments, only: [:create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :course
  validates :text, presence: true
end

app/models/course.rb
class Course < ApplicationRecord
  extend FriendlyId
  belongs_to :year
  has_many :comments
  friendly_id :uniqueslug

  def uniqueslug
    "#{url_name}-#{inner_index}"
  end
end

app/models/crawl_history.rb
class CrawlHistory < ApplicationRecord
end

app/models/year.rb
class Year < ApplicationRecord
  extend FriendlyId
  has_many :courses
  friendly_id :year
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def top_page
    @comments = Comment.all.order(created_at: 'DESC').limit(30)
    render template: 'top_page', layout: 'application', content_type: 'text/html'
  end

  def render_404
    render template: 'errors/error_404', status: 404, layout: 'application', content_type: 'text/html'
  end

  def crawl
    if CrawlHistory.all.empty? || CrawlHistory.last.created_at < Time.now.ago(1.day)
      CrawlHistory.create
      CampusCrawler::Handler.start_crawling(params[:year]&.to_i)
      return render plain: 'クロール完了'
    end
    render plain: 'クロール実行済み'
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    year_id               = params.require(:year_id)
    url_name, inner_index = params.require(:course_id).split(/-(?=\d+$)/)
    contributor           = params.require(:comment).require(:contributor)
    text                  = params.require(:comment).require(:text)
    @year   = Year.friendly.find(year_id)
    @course = @year.courses.find_by(url_name: url_name, inner_index: inner_index)
    @course.update(
      comment_count: @course.comment_count + 1
    )
    @course.comments.create(
      contributor: contributor,
      text: text
    )
    redirect_to [@year, @course]
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  MAIN_COLUMNS = [
    :comment_sort,
    :curriculum,
    :course_title_japanese,
    :course_title_english,
    :day_and_period,
    :timetable_code,
    :year_offerd,
    :semester_offerd,
    :faculty_offering_the_course,
    :credits,
    :category,
    :cluster_and_department,
    :lecturer,
    :query,
    :url_name
  ]

  SUB_COLUMNS = [ # 全検索で調べるカラム
   :course_title_japanese,
   :course_title_english,
   :topic_and_goals,
   :prerequisites,
   :recommended_prerequisites_and_preparation,
   :course_textbooks_and_materials,
   :course_outline_and_weekly_schedule,
   :course_content_utilizing_practical_experience,
   :preparation_and_review_outside_class,
   :evaluation_and_grading,
   :office_hours,
   :message_for_students,
   :other,
   :keyword
  ]

  def index
    @year       = Year.friendly.find(params.require(:year_id))
    @courses    = @year.courses.page(params[:page]).per(100)
    @pre_params = {}
  end

  def search
    params.permit!
    @year    = Year.friendly.find(params.require(:year_id))
    @courses = @year.courses.then{ |courses|
      params[:url_name].blank? ? courses : courses.where('url_name LIKE ?', params[:url_name] + '%')
    }.then { |courses|
      (MAIN_COLUMNS - [:curriculum, :credits, :comment_sort, :query, :url_name]).inject(courses) do |cou, col|
        params[col].blank? ? cou : cou.where("#{col} REGEXP ?", params[col])
      end
    }.then { |courses|
      if params[:curriculum].blank?
        courses
      else
        courses.where("curriculum LIKE ?", params[:curriculum] + '%')
      end
    }.then { |courses|
      n, o = *params[:credits]&.chars
      if n.blank?
        courses
      elsif o.nil?
        courses.where(credits: n)
      else
        courses.where('credits >= ?', n)
      end
    }.then { |courses|
      case params[:comment_sort]
      when 'desc' then courses.order('comment_count DESC')
      when 'new'  then courses.order('updated_at DESC')
      else             courses
      end
    }.then { |courses|
      if params[:query].blank?
        courses
      else
        params[:query].split(/[[:space:]]/).inject(courses) do |c, q|
          c.where("CONCAT(#{SUB_COLUMNS.join(',')}) LIKE ?", '%' + q + '%')
        end
      end
    }.page(params[:page]).per(100)
    @pre_params = MAIN_COLUMNS.map do |col|
      { col => params[col] }
    end.inject(:merge)
  end

  def show
    url_name, inner_index = params.require('id').split(/-(?=\d+$)/) # 末尾のハイフンで区切る
    year                  = params.require('year_id')
    @year                 = Year.friendly.find(year)
    @course               = @year.courses.find_by(url_name: url_name, inner_index: inner_index)
    @comments             = @course.comments
    @comment              = Comment.new
  end
end

app/controllers/years_controller.rb
class YearsController < ApplicationController
  def index
    @years = Year.all
  end

  def show
    @year = params.require(:id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nl2br(str)
    h(str).gsub(/\R/, "<br>")
  end
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/lecture_helper.rb
module LectureHelper
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/courses/_index_table.html.erb
<div class="container">

  <%= form_with(url: year_courses_search_path, local: true, method: :get, class: '') do |f| %>
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="form-group form-inline">
          <%= f.label('コメントソート', class: 'input-group-text', for: 'comment_sort') %>
          <%= f.select(:comment_sort, options_for_select({"-" => :none, '多い順' => :desc}, @pre_params[:comment_sort]), {}, class: 'form-control' ) %>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-8">
        <div class="form-group form-inline">
          <%= f.label('授業科目名', class: 'input-group-text', for: 'course_title_japanese') %>
          <%= f.text_field(:course_title_japanese, value: @pre_params[:course_title_japanese], placeholder: '正規|表現|ok', class: 'form-control', id: 'course_title_japanese')%>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="form-group form-inline">
          <%= f.label('課程', class: 'input-group-text', for: 'curriculum') %>
          <%= f.text_field :curriculum, value: @pre_params[:curriculum], placeholder: '', class: 'form-control', id: 'curriculum', list: 'curriculum_list' %>
          <datalist id="curriculum_list">
            <% '情報理工学域|情報理工学域夜間主コース|情報理工学部|情報理工学部夜間主コース　先端工学基礎課程|情報理工学研究科（博士前期課程）（2016～）|情報理工学研究科（博士後期課程）（2016～）|情報理工学研究科（博士前期課程）（2010～）|情報理工学研究科（博士後期課程）（2010～）|電気通信学部|電気通信学部　夜間主コース|電気通信学研究科（博士前期課程）|電気通信学研究科（博士後期課程）|情報システム学研究科（博士前期課程）|情報システム学研究科（博士後期課程）'.split('|').each do |d| %>
              <option value="<%= d %>">
            <% end %>
          </datalist>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-8">
        <div class="form-group form-inline">
          <%= f.label('英文授業科目名', class: 'input-group-text', for: 'course_title_english') %>
          <%= f.text_field(:course_title_english, value: @pre_params[:course_title_english], placeholder: '', class: 'form-control', id: 'course_title_english')%>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="form-group form-inline">
          <%= f.label('曜日・時限', class: 'input-group-text', for: 'day_and_period') %>
          <%= f.text_field :day_and_period, value: @pre_params[:day_and_period], placeholder: '', class: 'form-control', id: 'day_and_period', list: 'day_and_period_list' %>
          <datalist id="day_and_period_list">
            <% '他|他, 他|月1|月1, 月2|月1, 火1|月2|月2, 月3|月2, 月3, 月4|月2, 月4|月2, 木2|月2, 水4|月3|月3, 月4|月3, 月4, 水3, 水4|月3, 木2| 月3, 水3|月4|月4, 水4|月5|月5, 月6|木1|木2|木2, 木3, 木4|木3|木3, 木4|木4|木5|木5, 他|木6, 木7|水1|水2|水2, 水3, 水4|水2, 金4|水3|水3, 水4|水4|水5|水5, 水6|火1|火1, 火2|火2|火2, 火3|火2, 火3, 火4|火3|火3, 火4|火4|火5|金1|金1, 金2|金2|金2, 金3|金2, 金3, 金4|金3|金3, 金4|金4|金5'.split('|').each do |d| %>
              <option value="<%= d %>">
            <% end %>
          </datalist>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="form-group form-inline">
          <%= f.label('時間割コード', class: 'input-group-text', for: 'timetable_code') %>
          <%= f.text_field(:timetable_code, value: @pre_params[:timetable_code], placeholder: '', class: 'form-control', id: 'timetable_code')%>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="form-group form-inline">
          <%= f.label('開講年次', class: 'input-group-text', for: 'year_offerd') %>
          <%= f.text_field :year_offerd, value: @pre_params[:year_offerd], class: 'form-control', id: 'year_offerd', list: 'year_offerd_list' %>
          <datalist id="year_offerd_list">
            <% '1|1/2|1/2/3|1/2/3/4|2|2/3/4|3|3/4|4'.split('|').each do |d| %>
              <option value="<%= d %>">
            <% end %>
          </datalist>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="form-group form-inline">
          <%= f.label('開講学期', class: 'input-group-text', for: 'semester_offerd') %>
          <%= f.text_field :semester_offerd, value: @pre_params[:semester_offerd], class: 'form-control', id: 'semester_oferd', list: 'semester_offerd_list' %>
          <datalist id="semester_offerd_list">
            <% '前学期|後学期|通年'.split('|').each do |d| %>
              <option value="<%= d %>">
            <% end %>
          </datalist>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="form-group form-inline">
          <%= f.label('開講コース・課程', class: 'input-group-text', for: 'faculty_offering_the_course') %>
          <%= f.text_field :faculty_offering_the_course, value: @pre_params[:faculty_offering_the_course], class: 'form-control', id: 'faculty_offering_the_course', list: 'faculty_offering_the_course_list' %>
          <datalist id="faculty_offering_the_course_list">
            <% '情報理工学域'.split('|').each do |d| %>
              <option value="<%= d %>">
            <% end %>
          </datalist>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="form-group form-inline">
          <%= f.label('単位数', class: 'input-group-text', for: 'credits') %>
          <%= f.select(:credits, options_for_select([nil, *%W[1 2 3 4 5 1↑ 2↑ 3↑ 4↑ 5↑]], @pre_params[:credits]), {}, class: 'form-control', id: 'credits') %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="form-group form-inline">
          <%= f.label('科目区分', class: 'input-group-text', for: 'category') %>
          <%= f.text_field :category, value: @pre_params[:category], class: 'form-control', id: 'category', list: 'category_list' %>
          <datalist id="category_list">
            <% '実践教育科目|専門科目|教職科目|総合文化科目'.split('|').each do |d| %>
              <option value="<%= d %>">
            <% end %>
          </datalist>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="form-group form-inline">
          <%= f.label('開講学科・専攻', class: 'input-group-text', for: 'cluster_and_department') %>
          <%= f.text_field :cluster_and_department, value: @pre_params[:cluster_and_department], class: 'form-control', id: 'cluster_and_department', list: 'cluster_and_department_list' %>
          <datalist id="cluster_and_department_list">
            <% 'Ⅰ類|Ⅰ類/Ⅱ類|Ⅱ類|Ⅱ類/Ⅲ類|Ⅲ類|情報理工学域'.split('|').each do |d| %>
              <option value="<%= d %>">
            <% end %>
          </datalist>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="form-group form-inline">
          <%= f.label('担当教員名', class: 'input-group-text', for: 'lecturer') %>
          <%= f.text_field(:lecturer, value: @pre_params[:lecturer], placeholder: '', class: 'form-control', id: 'lecturer')%>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="form-group form-inline">
          <%= f.label('科目URL検索', class: 'input-group-text text-uppercase', for: 'url_name') %>
          <%= f.text_field(:url_name, value: @pre_params[:url_name], placeholder: '前方一致', class: 'form-control', id: 'query')%>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-5">
        <div class="form-group form-inline">
          <%= f.label('シラバス全文単語検索', class: 'input-group-text', for: 'query') %>
          <%= f.text_field(:query, value: @pre_params[:query], placeholder: '', class: 'form-control', id: 'query')%>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-3">
        <%= f.submit('検索', class: 'btn btn-outline-success') %>
      </div>
    </div>
  <% end %>
</div>

<br>
<div class="container">
  <%= paginate @courses %>
</div>

<table class="table table_index table-sm table-bordered">
  <thead class="thead-light">
    <tr class='header_row'>
      <th scope="row" class="comment_count row_tiny">💬</th>
      <th scope="row" class="curriculum row_tiny">課程</th>
      <th scope="row" class="course_title_japanese">授業科目名</th>
      <th scope="row" class="course_title_english">英文授業科目名</th>
      <th scope="row" class="day_and_period row_small">曜日・時限</th>
      <th scope="row" class="timetable_code row_small">時間割コード</th>
      <th scope="row" class="year_offerd row_small">開講年次</th>
      <th scope="row" class="semester_offerd row_small">開講学期</th>
      <th scope="row" class="faculty_offering_the_course">開講コース・課程</th>
      <th scope="row" class="credits row_tiny">単位数</th>
      <th scope="row" class="category">科目区分</th>
      <th scope="row" class="cluster_and_department">開講学科・専攻</th>
      <th scope="row" class="lecturer">担当教員名</th>
      <th scope="row" class="course_website">授業関連Webページ</th>
    </tr>
    <% @courses.each do |c| %>
      <tr>
        <td class='comment_count'><%= c.comment_count %></td>
        <td class='curriculum'><%= c.curriculum %></td>
        <td class='course_title_japanese'><%= link_to(c.course_title_japanese, url_for(controller: 'courses', action: 'show', id: c.uniqueslug))%></td>
        <td class='course_title_english'><%= c.course_title_english %></td>
        <td class='day_and_period'><%= c.day_and_period %></td>
        <td class='timetable_code'><%= c.timetable_code %></td>
        <td class='year_offerd'><%= c.year_offerd %></td>
        <td class='semester_offerd'><%= c.semester_offerd %></td>
        <td class='faculty_offering_the_course'><%= c.faculty_offering_the_course %></td>
        <td class='credits'><%= c.credits %></td>
        <td class='category'><%= c.category %></td>
        <td class='cluster_and_department'><%= c.cluster_and_department %></td>
        <td class='lecturer'><%= c.lecturer %></td>
        <td class='course_website' style="word-wrap:break-word;">
          <% if (urls = URI.extract(c.course_website, ['http', 'https'])).empty? %>
            <%= c.course_website %>
          <% else %>
             <% html = urls.inject(c.course_website) do |text, url| %>
               <% text.gsub(url , (link_to url, url)) %>
             <% end %>
             <%= raw html %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </thead>
</table>

<div class="container">
  <%= paginate @courses %>
</div>

app/views/courses/index.html.erb
<% breadcrumb :course_index %>
<%= breadcrumbs style: :bootstrap, pretext: '', separator: ' / ' %>

<% content_for(:html_title) { "#{@year.year}年のコース一覧" } %>

<%= render 'index_table' %>

app/views/courses/search.html.erb
<% breadcrumb :search_index %>
<%= breadcrumbs style: :bootstrap, pretext: '', separator: ' / ' %>

<% content_for(:html_title) { "#{@year.year}年のコース検索結果" } %>

<%= render 'index_table' %>

app/views/courses/show.html.erb
<div id='top'><div>
<% breadcrumb :course %>
<%= breadcrumbs style: :bootstrap, pretext: '', separator: ' / ' %>

<% content_for(:html_title) { @course.course_title_japanese } %>

<div class="container">
  <h1><%= @course.course_title_japanese %></h1>

  <%= link_to("同名科目を検索", year_courses_search_path(url_name: @course.url_name), class: 'btn btn-success', type: 'button') %>
  <a id="comments" class="btn btn-secondary" type="button" href='#bottom'>コメントを見る</a>
  <br>
  <br>

  <table class="table table_show">
    <thead class="thead-light">
      <tr>
        <th scope="row">授業科目名</th>
        <td colspan="3"><%= raw @course.course_title_japanese.then{|x|nl2br(x)} %></td>
      </tr>
      <tr>
        <th scope="row">課程</th>
        <td colspan="3"><%= raw @course.curriculum.then{|x|nl2br(x)} %></td>
      </tr>
      <tr>
        <th scope="row">英文授業科目名</th>
        <td><%= raw @course.course_title_english.then{|x|nl2br(x)} %></td>
        <th scope="row">曜日・時限</th>
        <td><%= raw @course.day_and_period.then{|x|nl2br(x)} %></td>
      </tr>
      <tr>
        <th scope="row">時間割コード</th>
        <td><%= raw @course.timetable_code.then{|x|nl2br(x)} %></td>
        <th scope="row">科目番号</th>
        <td><%= raw @course.code.then{|x|nl2br(x)} %></td>
      </tr>
      <tr>
        <th scope="row">開講年度</th>
        <td><%= raw @course.academic_year.then{|x|nl2br(x)} %></td>
        <th scope="row">開講年次</th>
        <td><%= raw @course.year_offerd.then{|x|nl2br(x)} %></td>
      </tr>
      <tr>
        <th scope="row">開講学期</th>
        <td><%= raw @course.semester_offerd.then{|x|nl2br(x)} %></td>
        <th scope="row">開講コース・課程</th>
        <td><%= raw @course.faculty_offering_the_course.then{|x|nl2br(x)} %></td>
      </tr>
      <tr>
        <th scope="row">授業の方法</th>
        <td><%= raw @course.teaching_method.then{|x|nl2br(x)} %></td>
        <th scope="row">単位数</th>
        <td><%= raw @course.credits.then{|x|nl2br(x)} %></td>
      </tr>
      <tr>
        <th scope="row">科目区分</th>
        <td><%= raw @course.category.then{|x|nl2br(x)} %></td>
        <th scope="row">開講学科・専攻</th>
        <td><%= raw @course.cluster_and_department.then{|x|nl2br(x)} %></td>
      </tr>
      <tr>
        <th scope="row">担当教員名</th>
        <td><%= raw @course.lecturer.then{|x|nl2br(x)} %></td>
        <th scope="row">居室</th>
        <td><%= raw @course.office.then{|x|nl2br(x)} %></td>
      </tr>
      <tr>
        <th scope="row">公開E-Mail</th>
        <td><%= raw @course.email.then{|x|nl2br(x)} %></td>
        <th scope="row">授業関連Webページ</th>
        <td style="word-break: break-all;">
          <% if (urls = URI.extract(@course.course_website, ['http', 'https'])).empty? %>
            <%= @course.course_website %>
          <% else %>
            <% html = urls.inject(@course.course_website) do |text, url| %>
              <% text.gsub(url , (link_to url, url)) %>
            <% end %>
          <%= raw html %>
          <% end %>
        </td>
      </tr>
      <tr>
        <th scope="row">更新日</th>
        <td><%= raw @course.last_updated.then{|x|nl2br(x)} %></td>
        <th scope="row">更新状況</th>
        <td><%= raw @course.update_status.then{|x|nl2br(x)} %></td>
      </tr>
      <tr>
        <th scope="row">主題および達成目標</th>
        <td colspan="3"><%= raw @course.topic_and_goals.then{|x|nl2br(x)} %></td>
      </tr>
      <tr>
        <th scope="row">前もって履修しておくべき科目</th>
        <td colspan="3"><%= raw @course.prerequisites.then{|x|nl2br(x)} %></td>
      </tr>
      <tr>
        <th scope="row">前もって履修しておくことが望ましい科目</th>
        <td colspan="3"><%= raw @course.recommended_prerequisites_and_preparation.then{|x|nl2br(x)} %></td>
      </tr>
      <tr>
        <th scope="row">教科書等</th>
        <td colspan="3"><%= raw @course.course_textbooks_and_materials.then{|x|nl2br(x)} %></td>
      </tr>
      <tr>
        <th scope="row">授業内容とその進め方</th>
        <td colspan="3"><%= raw @course.course_outline_and_weekly_schedule.then{|x|nl2br(x)} %></td>
      </tr>
      <tr>
        <th scope="row">実務経験を活かした授業内容(実務経験内容も含む)</th>
        <td colspan="3"><%= raw @course.course_content_utilizing_practical_experience.then{|x|nl2br(x)} %></td>
      </tr>
      <tr>
        <th scope="row">授業時間外の学習（予習・復習等）</th>
        <td colspan="3"><%= raw @course.preparation_and_review_outside_class.then{|x|nl2br(x)} %></td>
      </tr>
      <tr>
        <th scope="row">成績評価方法および評価基準（最低達成基準を含む）</th>
        <td colspan="3"><%= raw @course.evaluation_and_grading.then{|x|nl2br(x)} %></td>
      </tr>
      <tr>
        <th scope="row">オフィスアワー：授業相談</th>
        <td colspan="3"><%= raw @course.office_hours.then{|x|nl2br(x)} %></td>
      </tr>
      <tr>
        <th scope="row">学生へのメッセージ</th>
        <td colspan="3"><%= raw @course.message_for_students.then{|x|nl2br(x)} %></td>
      </tr>
      <tr>
        <th scope="row">その他</th>
        <td colspan="3"><%= raw @course.other.then{|x|nl2br(x)} %></td>
      </tr>
      <tr>
        <th scope="row">キーワード</th>
        <td colspan="3"><%= raw @course.keyword.then{|x|nl2br(x)} %></td>
      </tr>
    </thead>
  </table>

  <div class="my-3 p-3 bg-white rounded box-shadow">
    <h2 class="border-bottom border-gray pb-2 mb-0">コメント・感想</h2>
    <% @comments.each do |comment| %>
      <div class="media text-muted pt-3">
        <p class="media-body pb-3 mb-0 lh-125 border-bottom border-gray">
          <strong class="d-block text-gray-dark">@<%= comment.contributor  || '匿名' %></strong>
          <%= comment.created_at.strftime('%Y/%m/%d %H:%M') %><br>
          <%= raw comment.text.then{|x|nl2br(x)} %>
        </p>
      </div>
    <% end %>
  </div>

  <h2>コメント・感想の投稿</h2>
  <%= form_with(model: [@year, @course, @comment], local: true, id: 'search_form') do |f| %>
    <div class="form-group">
      <%= f.label '名前', for: 'name_field' %>
      <%= f.text_field :contributor, value: '匿名', class: 'form-control', id: 'name_field' %>
    </div>
    <div class="form-group">
      <label for="comment_field">コメント</label>
      <%= f.text_area :text, class: 'form-control', id: 'comment_field', rows: "3"%>
    </div>
    <%= f.submit('投稿する', class: 'btn btn-primary')%>
  <% end %>
  <br>
  <a id="bottom" class="btn btn-secondary" type="button" href='#top'>ページ先頭へ</a>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%# <title>UECCEU</title> %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application' %>
    <title><%= content_for?(:html_title) ? yield(:html_title) : 'UEC Campus Explorer Uploader' %></title>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/years/index.html.erb
<% breadcrumb :year_index %>
<%= breadcrumbs pretext: '', separator: ' / ' %>
<br>
<h1>年度一覧</h1>
<% @years.each do |y| %>
  <h2><%= link_to("#{y.year}年度", y) %></h2>
<% end %>

app/views/years/show.html.erb
<% breadcrumb :year %>
<%= breadcrumbs pretext: '', separator: ' / ' %>
<br>
<h1><%= @year %>年度のページ一覧</h1>
<h2><%= link_to '授業一覧', year_courses_path(year_id: @year) %></h2>